apiVersion: v1
kind: Service
metadata:
  name: lunch-service
  labels:
    app: lunch
spec:
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dinner-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: lunch  
    spec:
      containers: 
      - name: dinner
        image: vinhags/workshop-restaurant:dinner
        ports:
        - containerPort: 3000
      env:
      - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName

